"""""""""""""""""""""""""""""""""""""""
"" ViM configuration options.
"" 
"" This took days of tweaking, testing and playing with.
"" But I feel open enough to share the tools I use every day.
"""""""""""""""""""""""""""""""""""""""
set nocompatible                      " Vi Improved!

filetype off                          " We'll check file types later.
syntax on                             " Each language has its own syntax; respect it!

let mapleader=","                     " Let the leader be a comma!

nmap <silent> <leader>ev :e ~/.vimrc  " Edit my Vim configuration.
nmap <silent> <leader>sv :so ~/.vimrc  " Reload my Vim configuration.

set tabstop=2                         " My tab are lean, mean and two spaces.
set shiftwidth=2                      " Autoindent by two spaces automagically.
set expandtab ts=2 sw=2 ai            " Expands tabs into spaces with some intelligence and two spaces.
set autoindent                        " Turn on autoindenting.
set copyindent                        " Copy the previous indentation style on autoindent.
set number                            " Force line numbers.
set showmatch                         " Match brackets."
set encoding=utf-8                    " We ♥ UTF-8 stuff.
set softtabstop=2                     " Gently remove space when hitting backspace."
set hidden                            " Don't close tabs, instead hide them.
set wrapmargin=2
set textwidth=79
set background=dark                   " I live life like Bruce Wayne, in the dark.
colorscheme solarized
let g:solarized_termcolors=256
set directory=~/.vim/tmp              " Set the temporary path."
set foldmethod=syntax                 " Fold code according to syntax."
set foldcolumn=2                      " Give the folding symbol column about 2 spaces."
set foldminlines=20                   " Don't fold anything less than 20 lines."
set history=1000                      " The memory should be big, so keep a big history."
set undolevels=1000                   " Be ready to undo that bug."
set wildignore=*.swp,*.pyc,*.bak,*.class
set title
set visualbell
set noerrorbells
set nobackup
set noswapfile
set ruler                             " Be a MAN! and know where you are."
set smartcase                         " ignore case if search pattern is all lowercase,
set smarttab                          " insert tabs according to shiftwidth not tabstop"
set scrolloff=4                       " Only go 4 lines past the end."
set hlsearch                          " Show me what I'm searching for."
set incsearch                         " Over time, make my search continue."
set gdefault                          " I'm human, so of course my regexs are /g by nature."
set nolist
set pastetoggle=<F2>
set mouse=a
set relativenumber
set fileformats=unix
set formatoptions+=1

"" Toggle show/hide invisible chars
nnoremap <leader>i :set list!<cr>

"" Toggle line numbers
nnoremap <leader>N :setlocal number!<cr>

"" Set up Vundle.
set rtp+=~/.vim/bundle/vundle
call vundle#rc()

"" Bundles used in the system.
Bundle 'gmarik/vundle'
Bundle 'tpope/vim-fugitive'
Bundle 'tpope/vim-rails'
Bundle 'tpope/vim-bundler'
Bundle 'tpope/vim-unimpaired'
Bundle 'Indent-Guides'
Bundle 'kchmck/vim-coffee-script'
Bundle 'Align'
Bundle 'jQuery'
Bundle 'L9'
Bundle 'gmarik/github-search.vim'
Bundle 'DfrankUtil'
Bundle 'vimprj'
Bundle 'jiangmiao/auto-pairs'
Bundle 'FuzzyFinder'
Bundle 'scrooloose/nerdcommenter'
Bundle 'scrooloose/nerdtree'
Bundle 'OmniCppComplete'
Bundle 'jistr/vim-nerdtree-tabs'
Bundle 'msanders/snipmate.vim'
Bundle 'Command-T'
Bundle 'cmake.vim'
Bundle 'altercation/vim-colors-solarized'

filetype plugin indent on

" Tags to include as generated by ctags.
" Remake the tags by running `ctags -R -f <TAG_PATH> <INCLUDE_PATH>`
set tags+=~/.vim/tags/qt
set tags+=~/.vim/tags/kde
set tags+=~/.vim/tags/boost

" Configuration for autocomplete
autocmd FileType python set omnifunc=pythoncomplete#Complete
autocmd FileType javascript set omnifunc=javascriptcomplete#CompleteJS
autocmd FileType html set omnifunc=htmlcomplete#CompleteTags
autocmd FileType css set omnifunc=csscomplete#CompleteCSS
autocmd FileType xml set omnifunc=xmlcomplete#CompleteTags
autocmd FileType php set omnifunc=phpcomplete#CompletePHP
autocmd FileType c set omnifunc=ccomplete#CompleteCpp

